export interface Allocation {
    _id?: string;                // Generated by backend
    requestId: string;          // Reference to the original request
    driverId: string;           // Assigned driver
    vehicleId: string;          // Assigned vehicle
    startDate: string;          // Start date of the trek
    endDate: string;            // End date of the trek
    completed?: boolean;  
    updatedAt?: string | Date;
  }
  