export interface VehicleRequest {
  _id?: string;                   // Generated by backend
  requestingOfficer: string;     // Officer's name
  unit: string;                  // Department or unit of the officer
  purpose: string;               // Purpose of the trip
  projectGoalNumber: string;     // Project or goal number
  travelingDay: string;          // Start date of the trip
  returnDay: string;             // Return date
  cumulativeDays: number;        // Total days for the trip
  regions: string;               // Regions to be visited
  district: string;              // Districts
  villages: string;              // Villages
  remarks: string;               // Any additional comments
  status: 'Pending' | 'Approved' | 'Rejected' | 'Completed';  // Status of the request
  updatedAt?: string | Date;

  employeeName?: string;
}

